workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/pivotal-base-447808-q9/pokemon/train2_docker:latest
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY
        - name: WANDB_PROJECT
          value: $WANDB_PROJECT
        - name: WANDB_ENTITY
          value: $WANDB_ENTITY
