name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
        pip install -r requirements_dev.txt
        pip install dvc-gs

    - name: Auth with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Get data
      run: dvc pull --verbose

    - name: Unzip data
      run: |
        unzip rawdata.zip
        mkdir data/processed

    - name: preprocess
      run: |
        python3 src/pokemon_classification data/raw data/processed

    - name: Test with pytest
      run: |
        pytest -v